### ISSUE TITLE
Activity names should be double-quoted

### ISSUE THREAD

**Issue by bkoelman** [alexmg/Timingz#119]
I found that Chrome DevTools does not show timings when the names (coming from `Activity`) contain special characters like spaces, underscores, or colons. I suspect this can be solved by adding double quotes around the names used.

See https://ma.ttias.be/server-timings-chrome-devtools/.

**Comment by bkoelman** [comment]
It looks like that commit replaces special characters, instead of adding double quotes. According to the example at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing, it should:
> Server-Timing: cache;desc="Cache Read";dur=23.2

**Comment by alexmg** [comment]
Double quotes are already being applied to the description. Unfortunately, they don't work on the metric name which is expected to be a "token" made up only of certain characters.

https://w3c.github.io/server-timing/#the-server-timing-header-field

**Comment by bkoelman** [comment]
Ok I understand,  thanks.
